language:
  - ruby
  - perl
sudo: required
dist: trusty
os: linux
rvm: 2.0.0
perl: 5.18

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libc6-dbg libxml-parser-perl libxml-sax-perl
  - DEBIAN_FRONTEND=noninteractive sudo apt-get autoremove -y --purge
      bison
      comerr-dev
      erlang-dev
      flex
      libblas-dev
      libbz2-dev
      libdrm-dev
      libexpat1-dev
      libffi-dev
      libfl-dev
      libfontconfig1-dev
      libfreetype6-dev
      libgcrypt11-dev
      libgdbm-dev
      libgeos-dev
      libgl1-mesa-dev
      libgmp-dev
      libice-dev
      libicu-dev
      libidn11-dev
      libjack-dev
      libjack-jackd2-0
      libjack-jackd2-dev
      libjack0
      libjasper-dev
      libjbig-dev
      libjpeg8-dev
      libkrb5-dev
      libldap2-dev
      libltdl-dev
      liblzma-dev
      liblzo2-dev
      libmagic-dev
      libmemcached-dev
      libncurses5-dev
      libossp-uuid-dev
      libpcre3-dev
      libpq-dev
      libqt4-dev
      libqtwebkit-dev
      libsasl2-dev
      libsm-dev
      libsqlite0-dev
      libsqlite3-dev
      libtinfo-dev
      libwebp-dev
      libwmf-dev
      libx11-dev
      libxau-dev
      libxcb1-dev
      libxml2-dev
      libyaml-dev
      llvm-3.4
      mysql-common
      unixodbc-dev
      x11proto-core-dev
      x11proto-input-dev
      x11proto-kb-dev
      x11proto-xext-dev
      zlib1g-dev
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis-ci@linuxbrew.sh"
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - HOME=/home/linuxbrew
  - sudo mkdir $HOME
  - sudo chown "$USER:" $HOME
  - LINUXBREW=$HOME/.linuxbrew
  - mkdir -p $LINUXBREW/bin
  - git clone --depth=1 https://github.com/Linuxbrew/brew "$LINUXBREW/Homebrew"
  - ln -s ../Homebrew/bin/brew /home/linuxbrew/.linuxbrew/bin/
  - export PATH="$LINUXBREW/bin:$LINUXBREW/sbin:$PATH"
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - mkdir -p "$(dirname "$HOMEBREW_TAP_DIR")"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  # Fix error: Incorrect file permissions (664)
  - if [ -f "Formula/*.rb" ]; then
      chmod 0644 Formula/*.rb;
    fi
  - umask 022
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_VERBOSE=1 HOMEBREW_VERBOSE_USING_DOTS=1
  - env | grep TRAVIS | tee /tmp/travis.env
  - ulimit -n 1024

install:
  - brew install graphviz jdk parallel pigz
  - brew install homebrew/science/bbtools
  - brew install homebrew/science/fastqc
  - brew install homebrew/science/minimap
  - brew install homebrew/science/miniasm
  - brew install homebrew/science/poa
  - brew install homebrew/science/samtools
  - brew install homebrew/science/seqtk
  - brew install homebrew/science/sickle
  - brew install wang-q/tap/faops
  - brew install wang-q/tap/jrange
  - brew install wang-q/tap/jrunlist
  - brew install wang-q/tap/scythe
  - brew install wang-q/tap/sparsemem
  - brew install wang-q/tap/jellyfish@2.2.4
  - brew install wang-q/tap/quorum@1.1.1
  - brew install wang-q/tap/superreads
  - brew install wang-q/tap/dazz_db@20161112
  - brew install wang-q/tap/daligner@20170203
  - cpanm -nq --installdeps --with-develop .
  - cpanm -nq . # install App::Anchr prior as some commands need `anchr` in $PATH

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
