language: generic
os: linux
sudo: required
dist: trusty

before_install:
  # Install Linuxbrew
  - test -d $HOME/.linuxbrew/bin || git clone https://github.com/Linuxbrew/brew.git $HOME/.linuxbrew
  - PATH="$HOME/.linuxbrew/bin:$PATH"
  - echo 'export PATH="$HOME/.linuxbrew/bin:$PATH"' >>~/.bash_profile
  - export MANPATH="$(brew --prefix)/share/man:$MANPATH"
  - export INFOPATH="$(brew --prefix)/share/info:$INFOPATH"
  - brew --version
  - ulimit -n 1024
  # Install GCC
  - brew install gcc
  # Install others
  - brew install perl
  - brew link perl
  - curl -L https://cpanmin.us | perl - App::cpanminus
  - PERL_BREW=$(brew --prefix)/Cellar/$(brew list --versions perl | sed 's/ /\//')
  - export PATH="$PERL_BREW/bin:$PATH"
  - export PERL5LIB="$(brew --prefix)/lib/perl5/site_perl:$PERL5LIB"
  - curl -sSf https://build.travis-ci.org/files/rustup-init.sh | sh -s -- -y
  - export PATH=${TRAVIS_HOME}/.cargo/bin:$PATH

install:
  - brew tap brewsci/science
  - brew tap brewsci/bio
  - brew install graphviz jdk parallel pigz
  - brew install bbtools
  - brew install fastqc
  - brew install brewsci/bio/minimap
  - brew install brewsci/bio/miniasm
  - brew install brewsci/bio/masurca
  - brew install poa
  - brew install samtools
  - brew install sickle
  - brew install wang-q/tap/faops
  - brew install wang-q/tap/sparsemem
  - brew install wang-q/tap/dazz_db@20161112
  - brew install wang-q/tap/daligner@20170203
  - cargo install intspan
  - cpanm -nq --installdeps --with-develop .
  - cpanm -nq . # install App::Anchr prior as some commands need `anchr` in $PATH

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
