language:
  - perl
  - ruby
perl: "5.18"
os: linux
rvm: 2.0.0
sudo: required
dist: trusty

before_install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - sudo mkdir -p /home/linuxbrew
  - sudo chown "$USER" /home/linuxbrew
  - LINUXBREW=/home/linuxbrew/.linuxbrew
  - git clone --depth=1 https://github.com/Linuxbrew/brew.git "$LINUXBREW"
  - export PATH="$LINUXBREW/bin:$PATH"
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - mkdir -p "$(dirname "$HOMEBREW_TAP_DIR")"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - export HOMEBREW_DEVELOPER="1"
  - env | grep TRAVIS | tee /tmp/travis.env
  - export HOMEBREW_DEVELOPER="1"
  - ulimit -n 1024

install:
  - brew install graphviz jdk parallel pigz
  - brew install homebrew/science/bbtools
  - brew install homebrew/science/bedtools
  - brew install homebrew/science/fastqc
  - brew install homebrew/science/jellyfish
  - brew install homebrew/science/picard-tools
  - brew install homebrew/science/poa
  - brew install homebrew/science/samtools
  - brew install homebrew/science/seqtk
  - brew install homebrew/science/sickle
  - brew install wang-q/tap/faops
  - brew install wang-q/tap/jrunlist
  - brew install wang-q/tap/scythe
  - brew install wang-q/tap/quorum@1.1.1
  - brew install wang-q/tap/sparsemem
  - brew install wang-q/tap/superreads
  - brew install wang-q/tap/dazz_db@20161112
  - brew install wang-q/tap/daligner@20170203
  - cpanm -nq --installdeps --with-develop .
  - cpanm -nq . # install App::Anchr prior as some commands need `anchr` in $PATH

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
