language: perl
os: linux
sudo: required
dist: bionic
perl:
  - "5.24"

before_install:
  # Install Linuxbrew
  - git clone https://github.com/Homebrew/brew ~/.linuxbrew/Homebrew
  - mkdir ~/.linuxbrew/bin
  - ln -s ../Homebrew/bin/brew ~/.linuxbrew/bin
  - eval $(~/.linuxbrew/bin/brew shellenv)
  - brew --version
  - ulimit -n 1024
  # Install GCC
  - brew install gcc
  # Install others
  - brew install adoptopenjdk@11

install:
  - brew tap brewsci/science
  - brew tap brewsci/bio
  - brew install parallel pigz
  - brew install bbtools
  - brew install fastqc
  - brew install brewsci/bio/minimap
  - brew install brewsci/bio/miniasm
  - brew install brewsci/bio/masurca
  - brew install poa
  - brew install samtools
  - brew install sickle
  - brew install wang-q/tap/faops
  - brew install wang-q/tap/sparsemem
  - brew install wang-q/tap/dazz_db@20201008
  - brew install wang-q/tap/daligner@20201008
  - brew install wang-q/tap/intspan
  - brew unlink perl
  - cpanm -nq --installdeps --with-develop .
  - cpanm -nq . # install App::Anchr prior as some commands need `anchr` in $PATH

before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Build.PL
  - ./Build build
  - cover -test
after_success:
  - cover -report codecov
