#!/usr/bin/env perl
use strict;
use warnings;
use App::Anchr;

App::Anchr->run;

=head1 OVERVIEW

For help with App::Anchr, run "anchr help"

=cut

__END__

perl -I lib/ script/anchr

perl -I lib/ t/02-init.t
