#!/usr/bin/env perl
use strict;
use warnings;
use App::Anchr;

App::Anchr->run;

=head1 OVERVIEW

For help with App::Anchr, run "anchr help"

=cut

__END__

perl -I lib/ script/anchr

perl -I lib/ script/anchr dep
perl -I lib/ t/02-dep.t

perl -I lib/ script/anchr dazzname t/1_4.anchor.fasta -o stdout
perl -I lib/ t/03-dazzname.t

perl -I lib/ script/anchr show2ovlp t/1_4.renamed.fasta t/1_4.show.txt -o stdout
perl -I lib/ script/anchr show2ovlp t/1_4.renamed.fasta t/1_4.show.txt -r t/1_4.replace.tsv -o stdout
perl -I lib/ t/04-show2ovlp.t

perl -I lib/ script/anchr trim t/R1.fq.gz t/R2.fq.gz -b NAMES -o stdout | bash
perl -I lib/ t/05-trim.t

perl -I lib/ script/anchr superreads t/R1.fq.gz t/R2.fq.gz
bash superreads.sh
perl -I lib/ t/06-superreads.t

perl -I lib/ script/anchr overlap t/1_4.pac.fasta -o stdout
perl -I lib/ script/anchr overlap t/1_4.pac.fasta --idt 0.8 --len 2500 --serial -o stdout
perl -I lib/ script/anchr overlap t/1_4.pac.fasta --idt 0.8 --len 2500 --all -o stdout
perl -I lib/ t/07-overlap.t

perl -I lib/ script/anchr orient t/1_4.anchor.fasta t/1_4.pac.fasta -o stdout
perl -I lib/ t/09-orient.t

