name: Build

on: [ push ]

jobs:
  build:
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        perl: [ '5.34', '5.32', '5.30' ]

    steps:
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - uses: actions/checkout@v3
      - run: perl -V
      - run: cpanm --installdeps .
      - run: perl Build.PL
      - run: ./Build build
      - run: ./Build test
